### ISSUE TITLE
Uninitialized constant Module::Plausible

### ISSUE THREAD

**Issue by CucumisSativus** [hendrikschneider/jekyll-analytics#47]
Hello!

I installed `jekyll-analytics` in the version `0.1.14`. I followed the readme in order to set up Plausible analytics, but when I tried to build the page I encountered an error:
```
/usr/local/bundle/gems/jekyll-analytics-0.1.14/lib/jekyll-analytics.rb:8:in `block in inject': uninitialized constant Module::Plausible (NameError)
	from /usr/local/bundle/gems/jekyll-analytics-0.1.14/lib/jekyll-analytics.rb:7:in `each'
	from /usr/local/bundle/gems/jekyll-analytics-0.1.14/lib/jekyll-analytics.rb:7:in `inject'
	from /usr/local/bundle/gems/jekyll-analytics-0.1.14/lib/jekyll-analytics.rb:21:in `block in <top (required)>'
```

If I understand it correctly, it looks like the latest released version is from June, but the change which introduced `Plausible` is from October. 

Could you please make an release? :)
What do you think about auto releasing on merge to master? Could I help with it?

**Comment by ogjunkyard** [comment]
I'm also running into the same issue as @CucumisSativus.

**Comment by DavidS** [comment]
Until a new release with these changes is available, you can directly use the merge commit with the Plausible changes using this in your Gemfile:

```
  gem "jekyll-analytics", "~> 0.1", git: 'https://github.com/hendrikschneider/jekyll-analytics', ref: '40e09570dea80e3a9ecb0ad796aad1c434ff067c'
```

(See https://github.com/hendrikschneider/jekyll-analytics/commit/40e09570dea80e3a9ecb0ad796aad1c434ff067c for verification)

**Comment by FoxxMD** [comment]
@hendrikschneider  any chance of cutting a release for this? Having to use git within bundler increases complexity for my builds.
