### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mardy** [hendrikschneider/jekyll-analytics#9]
Hi, I just added jekyll-analytics to my site but when I run jekyll serve I get this:
```
$ jekyll s
/home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-analytics-0.1.7/lib/jekyll-analytics.rb:1:in `require': /home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-analytics-0.1.7/lib/analytics/Matomo.rb:4: syntax error, unexpected tIDENTIFIER, expecting keyword_end (SyntaxError)
    <script type="text/javascript">
                      ^
/home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-analytics-0.1.7/lib/analytics/Matomo.rb:4: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
<script type="text/javascript">
                              ^
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-analytics-0.1.7/lib/jekyll-analytics.rb:1:in `block in <top (required)>'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-analytics-0.1.7/lib/jekyll-analytics.rb:1:in `each'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-analytics-0.1.7/lib/jekyll-analytics.rb:1:in `<top (required)>'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `require'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `each'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:77:in `block in require'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `each'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:66:in `require'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.4/lib/bundler.rb:108:in `require'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-3.6.2/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
	from /home/mardy/.rvm/gems/ruby-2.4.0/gems/jekyll-3.6.2/exe/jekyll:11:in `<top (required)>'
	from /home/mardy/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `load'
	from /home/mardy/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `<main>'
	from /home/mardy/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/mardy/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by hendrikschneider** [comment]
Thank you :)

I have to check why my test didn't fail

**Comment by hendrikschneider** [comment]
I released a new version with your your fixtures :)
